import platform
import re
import sys
from distutils.core import Command
from pathlib import Path

from setuptools import find_packages, setup

python_version = ".".join(map(str, sys.version_info[:2]))
os_name = platform.system().lower()

REQUIREMENTS_DIR = Path(__file__).resolve().parent / "requirements"


def read_requirement_group(name):
    path = REQUIREMENTS_DIR / f"{name}.txt"
    return [
        line
        for raw_line in path.read_text(encoding="utf-8").splitlines()
        if (line := raw_line.strip()) and not line.startswith("#")
    ]


DEPENDENCY_GROUPS = {
    name: read_requirement_group(name)
    for name in (
        "comfy",
        "core",
        "dev",
        "serverless",
        "tensorrt",
        "ui",
        "vision",
        "web",
    )
}

torch_pins = {
    requirement.split("==", maxsplit=1)[0]: requirement.split("==", maxsplit=1)[1]
    for requirement in read_requirement_group("torch")
}
torch_version = torch_pins["torch"]
torchvision_version = torch_pins["torchvision"]

python_tags = {
    "3.8": "cp38",
    "3.9": "cp39",
    "3.10": "cp310",
    "3.11": "cp311",
}
if python_version not in python_tags:
    sys.exit(f"Unsupported Python version: {python_version}")

python_tag = python_tags[python_version]
if os_name == "linux":
    wheel_platform = "manylinux_2_28_x86_64"
elif os_name == "windows":
    wheel_platform = "win_amd64"
else:
    wheel_platform = None

if wheel_platform is None:
    torch_requirement = f"torch=={torch_version}"
    torchvision_requirement = f"torchvision=={torchvision_version}"
else:
    torch_filename = (
        f"torch-{torch_version}%2Bcu128-{python_tag}-{python_tag}-{wheel_platform}.whl"
    )
    torchvision_filename = (
        f"torchvision-{torchvision_version}%2Bcu128-"
        f"{python_tag}-{python_tag}-{wheel_platform}.whl"
    )
    torch_requirement = f"torch@https://download.pytorch.org/whl/cu128/{torch_filename}"
    torchvision_requirement = (
        f"torchvision@https://download.pytorch.org/whl/cu128/{torchvision_filename}"
    )

_deps = [torch_requirement, torchvision_requirement]
for dependency_group in DEPENDENCY_GROUPS.values():
    _deps.extend(dependency_group)

# this is a lookup table with items like:
#
# tokenizers: "huggingface-hub==0.8.0"
# packaging: "packaging"
#
# some of the values are versioned whereas others aren't.
pattern = re.compile(r"^([^@!=<>~]+)(?:[@!=<>~].*)?$")

deps = {match[0]: x for x in _deps for match in [pattern.findall(x)] if match}


# since we save this data in src/deforum/dependency_versions_table.py it can be easily accessed from
# anywhere. If you need to quickly access the data from this table in a shell, you can do so easily with:
#
# python -c 'import sys; from deforum.dependency_versions_table import deps; \
# print(" ".join([ deps[x] for x in sys.argv[1:]]))' tokenizers datasets
#
# Just pass the desired package names to that script as it's shown with 2 packages above.
#
# If deforum is not yet installed and the work is done from the cloned repo remember to add `PYTHONPATH=src` to the
# script above
#
# You can then feed this for example to `pip`:
#
# pip install -U $(python -c 'import sys; from deforum.dependency_versions_table import deps; \
# print(" ".join([ deps[x] for x in sys.argv[1:]]))' tokenizers datasets)
#

class DepsTableUpdateCommand(Command):
    """
    A custom distutils command that updates the dependency table.
    usage: python setup.py deps_table_update
    """

    description = "build runtime dependency table"
    user_options = [
        # format: (long option, short option, description).
        ("dep-table-update", None, "updates src/deforum/dependency_versions_table.py"),
    ]

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def run(self):
        entries = "\n".join([f'    "{k}": "{v}",' for k, v in deps.items()])
        content = [
            "# THIS FILE HAS BEEN AUTOGENERATED. To update:",
            "# 1. modify the files under requirements/",
            "# 2. run `python setup.py deps_table_update`",
            "deps = {",
            entries,
            "}",
            "",
        ]
        target = "src/deforum/dependency_versions_table.py"
        print(f"updating {target}")
        with open(target, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(content))


install_requires = [
    torch_requirement,
    torchvision_requirement,
    *DEPENDENCY_GROUPS["core"],
]

extras = {
    name: list(requirements)
    for name, requirements in DEPENDENCY_GROUPS.items()
    if name != "core"
}
extras["full"] = list(
    dict.fromkeys(
        requirement
        for name in ("tensorrt", "ui", "vision", "web")
        for requirement in DEPENDENCY_GROUPS[name]
    )
)

setup(
    name="deforum",
    version="0.1.9.dev1",  # expected format is one of x.y.z.dev0, or x.y.z.rc1 or x.y.z (no to dashes, yes to dots)
    description="State-of-the-art Animation Diffusion in PyTorch and TRT.",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    keywords="deep learning diffusion deforum pytorch stable diffusion",
    license="Apache",
    author="The Deforum team",
    author_email="deforum-art@deforum.com",
    url="https://github.com/deforum-studio/deforum",
    package_dir={"": "src"},
    packages=find_packages("src"),
    # package_data={"deforum": ["py.typed"]},
    include_package_data=True,
    python_requires=">=3.8.0",
    install_requires=list(install_requires),
    extras_require=extras,
    entry_points={"console_scripts": ["deforum=deforum.commands.deforum_cli:start_deforum_cli",
                                      "deforum-test=deforum.commands.deforum_test:start_deforum_test",
                                      "deforum-profile=deforum.commands.deforum_profiling:start_deforum_test"
                                      ]},
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    cmdclass={"deps_table_update": DepsTableUpdateCommand},
)

# Release checklist
# 1. Change the version in __init__.py and setup.py.
# 2. Commit these changes with the message: "Release: Release"
# 3. Add a tag in git to mark the release: "git tag RELEASE -m 'Adds tag RELEASE for pypi' "
#    Push the tag to git: git push --tags origin main
# 4. Run the following commands in the top-level directory:
#      python setup.py bdist_wheel
#      python setup.py sdist
# 5. Upload the package to the pypi test server first:
#      twine upload dist/* -r pypitest
#      twine upload dist/* -r pypitest --repository-url=https://test.pypi.org/legacy/
# 6. Check that you can install it in a virtualenv by running:
#      pip install -i https://testpypi.python.org/pypi deforum
#      deforum env
#      deforum test
# 7. Upload the final version to actual pypi:
#      twine upload dist/* -r pypi
# 8. Add release notes to the tag in GitHub once everything is looking deforumish.
# 9. Update the version in __init__.py, setup.py to the new version "-dev" and push to master
